variable "raspberrypi_ip" {}
variable "username" {}
variable "password" {}
variable "new_hostname" {}
variable "new_password" {}
variable "timezone" {}
variable "static_ip_and_mask" {}
variable "static_router" {}
variable "static_dns" {}